import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'

const capabilities = [
  { title: 'Distributed Backends & Microservices', tech: 'Java | Spring Boot | REST | Kafka | Redis | MySQL', copy: 'Architecting stateless, loosely coupled backend services with token-based authentication, event-driven pipelines, and optimized caching-layer schemas.' },
  { title: 'Type-Safe Client Applications', tech: 'React | Next.js | TypeScript | Vite | Tailwind', copy: 'Engineering modular, accessible interfaces focused on atomic state management, route optimization, and clean component isolation.' },
  { title: 'Cloud Native & DevOps Pipeline', tech: 'AWS | Docker | Terraform | GitHub Actions', copy: 'Automating build and deployment cycles with infrastructure as code and containerization for repeatable, high-availability production releases.' },
]

const works = [
  { title: 'AutoScale API', domain: 'Cloud infrastructure', stack: 'Spring Boot | AWS | Terraform' },
  { title: 'Sphere', domain: 'Full-stack platform', stack: 'React | Spring Boot | MySQL' },
  { title: 'DevSecOps Pipeline', domain: 'Delivery automation', stack: 'AWS | Docker | GitHub Actions' },
]

const topologyNodes = [
  { id: 'client', name: 'Client', stack: 'React / Next.js', telemetry: 'Type-safe React and Next.js interfaces built around accessible components, modular state, and route-level performance.' },
  { id: 'gateway', name: 'Gateway', stack: 'Spring Boot / JWT', telemetry: 'Spring Boot API boundaries secured with JWT/OAuth2 patterns, resilient validation, and clean service contracts.' },
  { id: 'events', name: 'Event Layer', stack: 'Kafka / Redis', telemetry: 'Kafka event streams and Redis caching designed for asynchronous processing and low-latency read paths.' },
  { id: 'cloud', name: 'Cloud Infra', stack: 'AWS / Docker', telemetry: 'Containerized AWS delivery pipelines with Terraform modules for repeatable, observable infrastructure.' },
]

export default function Home() {
  const [activeNode, setActiveNode] = useState('gateway')
  const [commandOpen, setCommandOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const selectedNode = topologyNodes.find((node) => node.id === activeNode) ?? topologyNodes[0]

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen((open) => !open) }
      if (event.key === 'Escape') setCommandOpen(false)
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  const copyEmail = async () => {
    await navigator.clipboard?.writeText('sumeetyadav@example.com')
    setCopied(true)
    window.setTimeout(() => setCopied(false), 1500)
  }

  return <>
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Serif+Display:ital@0;1&family=Inter:wght@400;500;600;700&display=swap');
      :root { color:#24221e; background:#f4f1ea; font-family:Inter,sans-serif; } * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; background:#f4f1ea; } a { color:inherit; }
      .shell { overflow-x:hidden; background:#f4f1ea; } .utility { height:76px; padding:0 clamp(22px,5vw,82px); position:sticky; top:0; z-index:50; display:grid; grid-template-columns:1fr auto 1fr; align-items:center; background:rgba(244,241,234,.80); backdrop-filter:blur(12px); border-bottom:1px solid rgba(36,34,30,.12); }.utility-left,.utility-right{display:flex;align-items:center;gap:13px}.utility-right{justify-content:flex-end}.brand{width:38px;height:38px;display:grid;place-items:center;border-radius:50%;background:#d9534f;text-decoration:none;font:500 .61rem 'DM Mono',monospace;letter-spacing:-.08em}.location{color:#756d60;font:.58rem 'DM Mono',monospace;letter-spacing:.06em;white-space:nowrap}.command-trigger,.availability-pill,.hero-action{border:1px solid #24221e;background:transparent;padding:9px 12px;color:#24221e;font:.57rem 'DM Mono',monospace;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;transition:background .2s,color .2s}.command-trigger:hover,.availability-pill:hover,.hero-action:hover{background:#1a1a1a;color:#f4f1ea}.availability-pill{border-radius:999px}.availability-pill i{display:inline-block;width:6px;height:6px;margin-right:7px;border-radius:50%;background:#d9534f}.command-dialog{position:fixed;inset:0;z-index:60;display:grid;place-items:start center;padding-top:min(20vh,180px);background:rgba(26,26,26,.25);backdrop-filter:blur(5px)}.command-panel{width:min(600px,calc(100% - 44px));border:1px solid #24221e;background:#f4f1ea;box-shadow:10px 10px 0 #1a1a1a}.command-panel header{padding:15px 18px;border-bottom:1px solid #24221e;font:.58rem 'DM Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#756d60}.command-panel a{display:flex;justify-content:space-between;align-items:center;padding:19px 18px;border-bottom:1px solid #c7bdab;text-decoration:none;font:400 1.65rem 'DM Serif Display',Georgia,serif;text-transform:uppercase}.command-panel a:last-child{border-bottom:0}.command-panel a:hover{background:#1a1a1a;color:#f4f1ea}.command-panel a span{font:.57rem 'DM Mono',monospace;color:#d9534f}
      .hero { min-height:calc(100vh - 76px); padding:clamp(70px,10vw,140px) clamp(22px,7vw,112px) 80px; display:grid; grid-template-columns:minmax(280px,5fr) minmax(430px,7fr); align-items:center; gap:clamp(40px,6vw,88px); }.badge { width:48px;height:48px;display:grid;place-items:center;border-radius:50%;background:#d9534f;font:500 .82rem 'DM Mono',monospace;position:relative }.badge:after{content:'';position:absolute;top:58px;left:0;width:210px;height:1px;background:#24221e}.availability{margin:20px 0 15px;font:.59rem 'DM Mono',monospace;letter-spacing:.1em;text-transform:uppercase}.availability i{display:inline-block;width:7px;height:7px;background:#d9534f;border-radius:50%;margin-right:8px}h1{margin:0;max-width:620px;font:400 clamp(3.35rem,5.8vw,6.4rem)/.87 'DM Serif Display',Georgia,serif;letter-spacing:-.055em}.role-highlight{display:inline-block;margin-top:9px;padding:5px 9px;background:#d9534f;font:.56em/.9 'DM Mono',monospace;letter-spacing:.02em;text-transform:uppercase;vertical-align:middle}.pitch{max-width:445px;margin:27px 0 0;font:italic clamp(1rem,1.35vw,1.22rem)/1.45 'DM Serif Display',Georgia,serif}.hero-actions{display:flex;gap:11px;flex-wrap:wrap;margin-top:30px}.hero-action{text-decoration:none}
      .topology{min-height:min(45vw,570px);padding:clamp(18px,2.8vw,34px);position:relative;overflow:hidden;background:#1a1a1a;color:#f4f1ea;box-shadow:12px 12px 0 #d9534f}.topology:before{content:'';position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 35%,rgba(99,151,116,.16),transparent 38%),linear-gradient(rgba(244,241,234,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(244,241,234,.04) 1px,transparent 1px);background-size:auto,32px 32px,32px 32px}.topology-header{position:relative;z-index:1;display:flex;justify-content:space-between;gap:14px;padding-bottom:16px;border-bottom:1px solid #575149;font:.64rem 'DM Mono',monospace;letter-spacing:.08em}.engine{color:#a9d9ad}.engine i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:6px;background:#80c98a;box-shadow:0 0 0 0 rgba(128,201,138,.6);animation:pulse 1.8s infinite}@keyframes pulse{70%{box-shadow:0 0 0 8px rgba(128,201,138,0)}100%{box-shadow:0 0 0 0 rgba(128,201,138,0)}}.topology-canvas{position:relative;z-index:1;min-height:330px;margin:10px 0}.topology-canvas svg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.topology-canvas path{stroke:#7f8d81;stroke-width:1.3;fill:none;stroke-dasharray:5 6}.topology-node{position:absolute;width:clamp(116px,15vw,154px);padding:13px;border:1px solid #7a746a;background:#20201e;color:#f4f1ea;text-align:left;cursor:pointer;transition:transform .22s,border-color .22s,box-shadow .22s,background .22s}.topology-node:hover,.topology-node.active{transform:translateY(-4px);border-color:#d9534f;background:#292720;box-shadow:0 0 0 1px #d9534f,0 0 25px rgba(217,83,79,.25)}.topology-node strong{display:block;margin-bottom:5px;font:400 1.2rem 'DM Serif Display',Georgia,serif}.topology-node span{color:#c6bda9;font:.53rem/1.4 'DM Mono',monospace}.node-client{left:4%;top:9%}.node-gateway{right:4%;top:9%}.node-events{left:4%;bottom:8%}.node-cloud{right:4%;bottom:8%}.telemetry{position:relative;z-index:1;min-height:78px;padding:13px;border-top:1px solid #575149;background:rgba(11,12,11,.72);font:.61rem/1.6 'DM Mono',monospace}.telemetry label{display:block;margin-bottom:4px;color:#d9534f;font-size:.53rem;letter-spacing:.08em}.telemetry strong{color:#a9d9ad;font-weight:400}
      .status-wrap{padding:clamp(40px,7vw,96px) clamp(22px,7vw,112px)}.status-bar{width:min(1280px,100%);margin:0 auto;padding:12px 16px;display:flex;justify-content:space-between;gap:18px;border:1px solid #24221e;background:#1a1a1a;color:#f4f1ea;font:.65rem 'DM Mono',monospace;letter-spacing:.08em;text-transform:uppercase}.status-bar span{min-width:0}.status-bar span:nth-child(2){text-align:center}.status-bar span:last-child{text-align:right;white-space:nowrap}.section{padding:clamp(68px,9vw,130px) clamp(22px,7vw,112px);border-top:1px solid #bdb4a3}.label{display:block;margin-bottom:16px;color:#756d60;font:.58rem 'DM Mono',monospace;letter-spacing:.13em;text-transform:uppercase}.section h2{max-width:700px;margin:0 0 45px;font:400 clamp(2.8rem,5vw,5.5rem)/.88 'DM Serif Display',Georgia,serif;letter-spacing:-.045em;text-transform:uppercase}.cap-grid{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid #24221e}.cap{min-height:290px;padding:27px;border-right:1px solid #24221e;transition:background .25s,color .25s}.cap:last-child{border:0}.cap:hover{background:#1a1a1a;color:#f4f1ea}.cap-num{color:#d9534f;font:.65rem 'DM Mono',monospace}.cap h3{margin:48px 0 12px;font:400 1.7rem/1 'DM Serif Display',Georgia,serif}.cap-tech{font:.59rem/1.6 'DM Mono',monospace;color:#8a8070}.cap:hover .cap-tech{color:#d9cba8}.cap p{font-size:.86rem;line-height:1.7;margin:22px 0 0}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #24221e}.metric{padding:26px;min-height:185px;border-right:1px solid #24221e}.metric:last-child{border:0}.metric strong{display:block;color:#d9534f;font:400 clamp(1.8rem,3.5vw,3.5rem)/1 'DM Serif Display',Georgia,serif}.metric span{display:block;margin-top:35px;font:.63rem/1.5 'DM Mono',monospace;text-transform:uppercase;letter-spacing:.08em}.index{background:#ded4c0}.works{border-top:1px solid #24221e}.work{min-height:86px;display:grid;grid-template-columns:1.1fr 1fr 1.25fr auto;align-items:center;gap:20px;border-bottom:1px solid #24221e;font:.63rem 'DM Mono',monospace}.work strong{font:400 clamp(1.35rem,2.2vw,2rem) 'DM Serif Display',Georgia,serif;text-transform:uppercase}.work a{text-decoration:none;text-transform:uppercase;font-size:.58rem}.work a:hover{color:#d9534f}.contact{background:#1a1a1a;color:#f4f1ea;display:grid;grid-template-columns:1fr auto;gap:40px;align-items:end}.contact .label{color:#d9cba8}.contact h2{max-width:760px;margin-bottom:0}.contact-links{display:grid;gap:12px}.contact-links a{color:#f4f1ea;font:.7rem 'DM Mono',monospace;text-decoration:none;text-align:right}.contact-links a:hover{color:#d9534f}.footer{padding:22px clamp(22px,7vw,112px);background:#1a1a1a;color:#b8b0a4;border-top:1px solid #4b4943;display:flex;justify-content:space-between;gap:20px;font:.6rem 'DM Mono',monospace}.footer q{font-style:italic}
      @media(max-width:900px){.hero{grid-template-columns:1fr;min-height:auto}.topology{min-height:540px;max-width:720px}.cap-grid,.metrics{grid-template-columns:1fr 1fr}.cap:nth-child(2),.metric:nth-child(2){border-right:0}.cap:last-child,.metric:last-child{border-top:1px solid #24221e}}@media(max-width:767px){.utility{grid-template-columns:1fr auto}.command-trigger{display:none}.location{font-size:.5rem}.hero,.section{padding-left:22px;padding-right:22px}.hero{padding-top:70px}.status-wrap{padding:48px 22px}.status-bar{display:grid;gap:8px;font-size:.52rem}.status-bar span:nth-child(2),.status-bar span:last-child{text-align:left}.topology{min-height:430px;padding:18px;box-shadow:8px 8px 0 #d9534f}.topology-header{font-size:.52rem}.topology-canvas{min-height:255px}.topology-node{width:43%;padding:10px}.topology-node strong{font-size:1rem}.topology-node span{font-size:.47rem}.node-client,.node-events{left:0}.node-gateway,.node-cloud{right:0}.telemetry{font-size:.54rem}.cap-grid,.metrics{grid-template-columns:1fr}.cap,.metric{border-right:0;border-bottom:1px solid #24221e}.cap:last-child,.metric:last-child{border-bottom:0}.cap h3{margin-top:34px}.contact{grid-template-columns:1fr}.contact-links a{text-align:left}.footer{padding:22px;flex-direction:column}.work{grid-template-columns:1fr;gap:7px;padding:18px 0}.work a{margin-top:5px}}
    `}</style>
    <main className="shell">
      <header className="utility"><div className="utility-left"><a className="brand" href="#top">&lt;SY/&gt;</a><span className="location">MUMBAI, IN (UTC+5:30)</span></div><button className="command-trigger" onClick={() => setCommandOpen(true)} aria-haspopup="dialog">[ CMD+K ] QUICK NAV</button><div className="utility-right"><button className="availability-pill" onClick={copyEmail}><i/>{copied ? 'Copied!' : 'Available for work'}</button></div></header>
      <AnimatePresence>{commandOpen && <motion.div className="command-dialog" role="dialog" aria-modal="true" aria-label="Quick navigation" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={() => setCommandOpen(false)}><motion.div className="command-panel" initial={{y:-16,opacity:0}} animate={{y:0,opacity:1}} exit={{y:-16,opacity:0}} onMouseDown={(event) => event.stopPropagation()}><header>Quick Nav / Esc to close</header><a href="#top" onClick={() => setCommandOpen(false)}><span>01 /</span>Home</a><a href="#capabilities" onClick={() => setCommandOpen(false)}><span>02 /</span>Capabilities</a><a href="/projects"><span>03 /</span>Featured Work</a><a href="#contact" onClick={() => setCommandOpen(false)}><span>04 /</span>Contact</a></motion.div></motion.div>}</AnimatePresence>
      <section className="hero" id="top"><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="badge">&lt;/&gt;</div><div className="availability"><i/>Available for full-time roles | Mumbai, IN</div><h1>Sumeet Yadav<br/><span className="role-highlight">Full Stack Engineer</span></h1><p className="pitch">Designing high-throughput backends with Spring Boot, responsive React interfaces, and automated AWS cloud pipelines.</p><div className="hero-actions"><a className="hero-action" href="#capabilities">[ Explore Architecture Down ]</a><button className="hero-action" onClick={copyEmail}>[ {copied ? 'Copied!' : 'Copy Email'} ]</button></div></motion.div>
        <motion.div className="topology" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{duration:.8,delay:.16}}><div className="topology-header"><span>// SYSTEM_TOPOLOGY.v2</span><span className="engine"><i/>ENGINE_ONLINE</span></div><div className="topology-canvas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M22 26 L78 26 L22 74 L78 74 M22 26 L78 74 M78 26 L22 74" /></svg>{topologyNodes.map(node => <button key={node.id} className={`topology-node node-${node.id}${activeNode === node.id ? ' active' : ''}`} onMouseEnter={() => setActiveNode(node.id)} onFocus={() => setActiveNode(node.id)} onClick={() => setActiveNode(node.id)}><strong>{node.name}</strong><span>{node.stack}</span></button>)}</div><AnimatePresence mode="wait"><motion.div className="telemetry" key={selectedNode.id} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.18}}><label>TELEMETRY / {selectedNode.name.toUpperCase()}</label><strong>{selectedNode.telemetry}</strong></motion.div></AnimatePresence></motion.div>
      </section>
      <div className="status-wrap"><div className="status-bar"><span>[ Status: Distributed Services Online ]</span><span>// Region: ap-south-1 (Mumbai)</span><span>Latency: ~28ms</span></div></div>
      <section id="capabilities" className="section"><span className="label">01 / System architecture & capabilities</span><h2>Build systems that remain clear under load.</h2><div className="cap-grid">{capabilities.map((cap,index) => <article className="cap" key={cap.title}><span className="cap-num">0{index + 1}</span><h3>{cap.title}</h3><span className="cap-tech">{cap.tech}</span><p>{cap.copy}</p></article>)}</div></section>
      <section className="section"><span className="label">02 / Engineering outcomes</span><div className="metrics"><div className="metric"><strong>&lt; 50ms</strong><span>Sub-50ms API Latency (Redis Caching)</span></div><div className="metric"><strong>Event-Driven</strong><span>Kafka Asynchronous Pipelines</span></div><div className="metric"><strong>100% IaC</strong><span>Terraform Infrastructure Modules</span></div><div className="metric"><strong>High Availability</strong><span>Containerized Rolling Deployments on AWS</span></div></div></section>
      <section id="work" className="section index"><span className="label">04 / Index</span><h2>Selected work, available in full.</h2><div className="works">{works.map(work => <article className="work" key={work.title}><strong>{work.title}</strong><span>{work.domain}</span><span>{work.stack}</span><a href="/projects">View Details -&gt;</a></article>)}</div></section>
      <section id="contact" className="section contact"><div><span className="label">05 / Quick contact</span><h2>Building something ambitious? Let's connect.</h2></div><div className="contact-links"><a href="mailto:sumeetyadav@example.com">Direct Email -&gt;</a><a href="https://github.com/Sumeet-Y1">GitHub -&gt;</a><a href="https://linkedin.com/in/sumeet-backenddev">LinkedIn -&gt;</a><a href="/projects">Featured Work -&gt;</a></div></section>
      <footer className="footer"><span>&lt;SY/&gt; / 2026</span><q>Good software should feel dependable, scale with confidence, and solve problems without friction.</q></footer>
    </main>
  </>
}
